name: AutoService SB construcao e teste

on:
  push:
    branches:
      - "main"
jobs:
  construir:
    runs-on: ubuntu-latest
    steps:
      - name: baixar o código
        uses: actions/checkout@v4
      - name: configurando o jar
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'oracle'
      - name: executar o maven
        run: mvn clean install -DskipTests